### ISSUE TITLE
Support async task

### ISSUE THREAD

**Issue by boly38** [creharmony/node-hook-action#4]
## Need
Default action are synchronized shell tasks

As user I would like a way to configure async task

## TODO list
- [x] add an extra and optional "async" flag for an action (into config file)
- [x] update [server](https://github.com/creharmony/node-hook-action/blob/main/src/server.js#L134) to support async case. [shelljs async example](https://gist.github.com/davidrleonard/2962a3c40497d93c422d1269bcd38c8f)

support async case:
- [x] POST an async task will result in a response with `201 Created` http status
- [x] POST an async task will result in a response with header `Location` with a generated unique async action id related endpoint
- [x]  async action handler will store action id, then start a shell with the action, and at the end, store the task result with unique ID as key. Store is in-memory.
- [x] GET `/actions/` endpoint will return pending and done async actions.
- [x] GET `/actions/<uniqueId>` endpoint will accept unique id and support following use-cases:
- - 200 action is done and payload include action result ( json format)
- - 202 action is still in progress
- - 400 one parameter (id) is invalid
- - 404 not action found with this id
- [x] GET endpoints must be secure by checking `x-token` header
